import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  loginscreen: {
    flex: 1,
    backgroundColor: '#EEF1FF',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    width: '100%',
  },
  loginheading: {
    fontSize: 26,
    marginBottom: 10,
  },
  logininputContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logininput: {
    borderWidth: 1,
    width: '90%',
    padding: 8,
    borderRadius: 2,
  },
  loginbutton: {
    backgroundColor: 'green',
    padding: 12,
    marginVertical: 10,
    width: '60%',
    borderRadius: 300,
    elevation: 1,
  },
  loginbuttonText: {
    textAlign: 'center',
    color: '#fff',
    fontWeight: '600',
  },
  chatscreen: {
    backgroundColor: '#F7F7F7',
    flex: 1,
    padding: 24,
    // paddingTop: 50,
    position: 'relative',
  },
  chatheading: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'green',
  },
  chattopContainer: {
    backgroundColor: '#F7F7F7',
    height: 70,
    width: '100%',
    padding: 20,
    justifyContent: 'center',
    marginBottom: 15,
    elevation: 2,
  },
  chatheader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  chatlistContainer: {
    paddingHorizontal: 0,
    marginTop: 16,
  },
  chatemptyContainer: {
    width: '100%',
    height: '80%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatemptyText: {
    fontWeight: 'bold',
    color: '#000',
    fontSize: 24,
    paddingBottom: 30,
  },
  messagingscreen: {
    flex: 1,
    backgroundColor: '#fff',
  },
  messaginginputContainer: {
    width: '100%',
    // Height: 60,
    // backgroundColor: "white",
    paddingBottom: 15,
    paddingHorizontal: 15,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  messaginginput: {
    // borderWidth: 1,
    // borderColor: "#1F1F1F",
    padding: 10,
    flex: 1,
    maxHeight: 110,
    color: '#000',
    backgroundColor: '#EFEFEF',
    marginRight: 10,
    // borderRadius: 20,
  },
  messagingbuttonContainer: {
    width: '30%',
    backgroundColor: 'green',
    borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
  },
  modalbutton: {
    width: '40%',
    height: 45,
    backgroundColor: '#1F2067',
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
  },
  modalbuttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  modaltext: {
    color: '#fff',
  },
  modalContainer: {
    width: '100%',
    borderTopColor: '#ddd',
    borderTopWidth: 1,
    elevation: 1,
    height: 400,
    backgroundColor: '#fff',
    position: 'absolute',
    left: 25,
    bottom: 0,
    zIndex: 10,
    paddingVertical: 50,
    paddingHorizontal: 20,
  },
  modalinput: {
    borderWidth: 2,
    padding: 15,
    color: '#fff',
  },
  modalsubheading: {
    color: '#000',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  mmessageWrapper: {
    width: '100%',
    alignItems: 'flex-start',
    marginBottom: 15,
  },
  mmessage: {
    maxWidth: '80%',
    backgroundColor: '#E9E9F0',
    paddingHorizontal: 15,
    paddingTop: 15,
    minWidth: 70,
    paddingBottom: 20,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    marginBottom: 2,
  },
  mavatar: {
    marginRight: 15,
    width: 40,
    height: 40,
    borderRadius: 50,
  },
  mavatar2: {
    marginLeft: 5,
  },
  cchat: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 15,
    paddingRight: 15,
    paddingLeft: 5,
    backgroundColor: '#fff',
    height: 80,
    marginBottom: 10,
  },
  cavatar: {
    marginRight: 15,
  },
  cusername: {
    fontSize: 18,
    marginBottom: 5,
    fontWeight: 'bold',
    color: '#000',
  },
  cmessage: {
    fontSize: 14,
    opacity: 0.7,
    color: '#000',
  },
  crightContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
  },
  ctime: {
    opacity: 0.5,
  },
  pageHeading: {
    fontSize: 23,
    // fontWeight: '700',
    color: '#000',
    fontFamily: 'TitilliumWeb-Bold',
  },
  pageSubHeading: {
    fontSize: 15,
    color: '#8F8F8F',
    marginTop: 8,
  },
  optionBox: {
    marginTop: 33,
  },
  modalContainerImage: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  modalCloseButtonImage: {
    position: 'absolute',
    top: 20,
    right: 20,
    zIndex: 1,
  },
  modalImage: {
    width: 390,
    height: 390,
    borderRadius: 10,
  },
});
